"""add tabela Posicoes

Revision ID: 34cb065a7ec3
Revises: 5be3960c2a1a
Create Date: 2023-01-23 22:27:56.343837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cb065a7ec3'
down_revision = '5be3960c2a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('precoMedio', sa.Float(), nullable=True),
    sa.Column('valorInvestido', sa.Float(), nullable=True),
    sa.Column('posicaoAtual', sa.Float(), nullable=True),
    sa.Column('lucroPrejuizo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tbl_teste')
    op.alter_column('Ativos', 'valor',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('Ativos', 'papel',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('Ativos', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Ativos', 'tipo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('Ativos', 'papel',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('Ativos', 'valor',
               existing_type=sa.REAL(),
               nullable=False)
    op.create_table('tbl_teste',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.drop_table('Posicoes')
    # ### end Alembic commands ###
