"""redefinido tabela compra e Posicao

Revision ID: 9a9d6b1ab768
Revises: abf962063955
Create Date: 2024-01-27 15:50:21.468921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9d6b1ab768'
down_revision = 'abf962063955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Compras', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.add_column('Compras', sa.Column('id_ativo', sa.Integer(), nullable=False))
    op.add_column('Compras', sa.Column('preco_unitario', sa.Float(), nullable=False))
    op.add_column('Compras', sa.Column('quantidade', sa.Integer(), nullable=False))
    op.add_column('Compras', sa.Column('data_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'Compras', 'Users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'Compras', 'Ativos', ['id_ativo'], ['id'])
    op.drop_column('Compras', 'idAtivo')
    op.add_column('Posicoes', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.add_column('Posicoes', sa.Column('id_ativo', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Posicoes', 'Users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'Posicoes', 'Ativos', ['id_ativo'], ['id'])
    op.drop_column('Posicoes', 'valorInvestido')
    op.drop_column('Posicoes', 'lucroPrejuizo')
    op.drop_column('Posicoes', 'nome')
    op.drop_column('Posicoes', 'precoMedio')
    op.drop_column('Posicoes', 'valor')
    op.drop_column('Posicoes', 'posicaoAtual')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posicoes', sa.Column('posicaoAtual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Posicoes', sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Posicoes', sa.Column('precoMedio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Posicoes', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Posicoes', sa.Column('lucroPrejuizo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Posicoes', sa.Column('valorInvestido', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Posicoes', type_='foreignkey')
    op.drop_constraint(None, 'Posicoes', type_='foreignkey')
    op.drop_column('Posicoes', 'id_ativo')
    op.drop_column('Posicoes', 'id_usuario')
    op.add_column('Compras', sa.Column('idAtivo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Compras', type_='foreignkey')
    op.drop_constraint(None, 'Compras', type_='foreignkey')
    op.drop_column('Compras', 'data_compra')
    op.drop_column('Compras', 'quantidade')
    op.drop_column('Compras', 'preco_unitario')
    op.drop_column('Compras', 'id_ativo')
    op.drop_column('Compras', 'id_usuario')
    # ### end Alembic commands ###
